import React from 'react'
import {Pie,Cell,PieChart,ResponsiveContainer,Legend} from 'recharts'
function PieChartStatistika({statistika}) {
    return (
    <ResponsiveContainer width='100%' aspect={1} >{/*stavimo kao kod slike*/}
        <PieChart width='100%' height='100%' >
            <Pie data={statistika} dataKey="value" nameKey="name" cx="50%" cy="50%" innerRadius={50} outerRadius={80} endAngle={0} startAngle={360} label>
            {
                statistika.map((data,index)=>(
                    <Cell key={data.name} fill={(index===0)? '#008000': '#FF0000'}/>
                ))
            }
        </Pie>
        {
            ((statistika[0].value+statistika[1].value)!==0)?//ako su obe vrijednosti 0 onda neće bit prikazan chart pa nema smisla da bude prikazana legenda
            <Legend verticalAlign="bottom" />/*By default, the content of the legend is generated by the name of Line, Bar, Area, etc. Alternatively, if no name has been set, the dataKey will be used to generate legend content.*/
            :
            null
        }
        </PieChart>
    </ResponsiveContainer>
    )
}

export default PieChartStatistika
