const tim=[//niz koji sadrzi domaci i gostujuci tim-> u taj obejtk ce jos dodatno ici timid i naziv jer zasad to biramo iz ponudenih timova u vodenje statistike al će u takvom obliku stizati s backenda
    {
    Igraci:[
        {
            maticni_broj:'128852',
            broj_dresa:6,
            ime:'Mislav',
            prezime:'Ivanda'
        },
        {
            maticni_broj:'12852',
            broj_dresa:6,
            ime:'Mislav',
            prezime:'Ivanda'
        },
        {
            maticni_broj:'12885',
            broj_dresa:6,
            ime:'Mislav',
            prezime:'Ivanda'
        },
        {
            maticni_broj:'18852',
            broj_dresa:6,
            ime:'Mislav',
            prezime:'Ivanda'
        },
        {
            maticni_broj:'28852',
            broj_dresa:6,
            ime:'Mislav',
            prezime:'Ivanda'
        },
        {
            maticni_broj:'1282',
            broj_dresa:6,
            ime:'Mislav',
            prezime:'Ivanda'
        },
        {
            maticni_broj:'122',
            broj_dresa:6,
            ime:'Mislav',
            prezime:'Ivanda'
        },
        {
            maticni_broj:'2885',
            broj_dresa:6,
            ime:'Mislav',
            prezime:'Ivanda'
        },
        {
            maticni_broj:'8852',
            broj_dresa:6,
            ime:'Mislav',
            prezime:'Ivanda'
        },
        {
            maticni_broj:'2852',
            broj_dresa:6,
            ime:'Mislav',
            prezime:'Ivanda'
        },
        {
            maticni_broj:'852',
            broj_dresa:6,
            ime:'Mislav',
            prezime:'Ivanda'
        },
        {
            maticni_broj:'188',
            broj_dresa:6,
            ime:'Mislav',
            prezime:'Ivanda'
        }
    ],
    Golmani:[  
    {
        maticni_broj:'1282',
        broj_dresa:6,
        ime:'Mislav',
        prezime:'Ivanda'
    },
    {
        maticni_broj:'1252',
        broj_dresa:6,
        ime:'Mislav',
        prezime:'Ivanda'
    },
    {
        maticni_broj:'152',
        broj_dresa:6,
        ime:'Mislav',
        prezime:'Ivanda'
    }],
    Treneri:[
        {
            maticni_broj:'1252',
            ime:'Mislav',
            prezime:'Ivanda'
        },
        {
            maticni_broj:'18852',
            broj_dresa:6,
            ime:'Mislav',
            prezime:'Ivanda'
        }
    ],
    Sluzbeni:[
        {
            maticni_broj:'1852',
            ime:'Mislav',
            prezime:'Ivanda'
        },
        {
            maticni_broj:'188',
            ime:'Mislav',
            prezime:'Ivanda'
        },
        {
            maticni_broj:'128',
            ime:'Mislav',
            prezime:'Ivanda'
        }
    ],
    Tehniko:[
        {
            maticni_broj:'152',
            ime:'Mislav',
            prezime:'Ivanda'
        },
        {
            maticni_broj:'852',
            ime:'Mislav',
            prezime:'Ivanda'
        },
        {
            maticni_broj:'28852',
            ime:'Mislav',
            prezime:'Ivanda'
        }
    ],
    Fiziotarapeut:[
        {
            maticni_broj:'152',
            ime:'Mislav',
            prezime:'Ivanda'
        },
        {
            maticni_broj:'122',
            ime:'Mislav',
            prezime:'Ivanda'
        },
        {
            maticni_broj:'1288',
            ime:'Mislav',
            prezime:'Ivanda'
        }
    ]
},
{
    Igraci:[
        {
            maticni_broj:'120052',
            broj_dresa:6,
            ime:'Mislav',
            prezime:'Ivanda'
        },
        {
            maticni_broj:'1784152',
            broj_dresa:6,
            ime:'Mislav',
            prezime:'Ivanda'
        },
        {
            maticni_broj:'987485',
            broj_dresa:6,
            ime:'Mislav',
            prezime:'Ivanda'
        },
        {
            maticni_broj:'3965152',
            broj_dresa:6,
            ime:'Mislav',
            prezime:'Ivanda'
        },
        {
            maticni_broj:'2041552',
            broj_dresa:6,
            ime:'Mislav',
            prezime:'Ivanda'
        },
        {
            maticni_broj:'12827402',
            broj_dresa:6,
            ime:'Mislav',
            prezime:'Ivanda'
        },
        {
            maticni_broj:'1782369',
            broj_dresa:6,
            ime:'Mislav',
            prezime:'Ivanda'
        },
        {
            maticni_broj:'2703655',
            broj_dresa:6,
            ime:'Mislav',
            prezime:'Ivanda'
        },
        {
            maticni_broj:'874102',
            broj_dresa:6,
            ime:'Mislav',
            prezime:'Ivanda'
        },
        {
            maticni_broj:'284360',
            broj_dresa:6,
            ime:'Mislav',
            prezime:'Ivanda'
        },
        {
            maticni_broj:'8570256',
            broj_dresa:6,
            ime:'Mislav',
            prezime:'Ivanda'
        },
        {
            maticni_broj:'187803',
            broj_dresa:6,
            ime:'Mislav',
            prezime:'Ivanda'
        }
    ],
    Golmani:[  
    {
        maticni_broj:'132642',
        broj_dresa:6,
        ime:'Mislav',
        prezime:'Ivanda'
    },
    {
        maticni_broj:'174552',
        broj_dresa:6,
        ime:'Mislav',
        prezime:'Ivanda'
    },
    {
        maticni_broj:'11254',
        broj_dresa:6,
        ime:'Mislav',
        prezime:'Ivanda'
    }],
    Treneri:[
        {
            maticni_broj:'178552',
            ime:'Mislav',
            prezime:'Ivanda'
        },
        {
            maticni_broj:'18702352',
            broj_dresa:6,
            ime:'Mislav',
            prezime:'Ivanda'
        }
    ],
    Sluzbeni:[
        {
            maticni_broj:'1852896',
            ime:'Mislav',
            prezime:'Ivanda'
        },
        {
            maticni_broj:'18871057',
            ime:'Mislav',
            prezime:'Ivanda'
        },
        {
            maticni_broj:'1280369',
            ime:'Mislav',
            prezime:'Ivanda'
        }
    ],
    Tehniko:[
        {
            maticni_broj:'325452',
            ime:'Mislav',
            prezime:'Ivanda'
        },
        {
            maticni_broj:'7852',
            ime:'Mislav',
            prezime:'Ivanda'
        },
        {
            maticni_broj:'23852',
            ime:'Mislav',
            prezime:'Ivanda'
        }
    ],
    Fiziotarapeut:[
        {
            maticni_broj:'15698',
            ime:'Mislav',
            prezime:'Ivanda'
        },
        {
            maticni_broj:'122741',
            ime:'Mislav',
            prezime:'Ivanda'
        },
        {
            maticni_broj:'12408',
            ime:'Mislav',
            prezime:'Ivanda'
        }
    ]
}
]



export default tim;