import klub1 from '../images/zagreb.jpg';
import klub2 from '../images/barcelona.png';
const utakmica={
    broj_utakmice:13268533,
    kolo:3,
    natjecanje: {id:1,naziv:'Premijer liga(Muški)'},
    datum:'22.12.2020',
    vrijeme:'19:00',
    gledatelji:300,
    lokacija:'SPALADIUM ARENA SPLIT',
    nadzornik: {maticni_broj:159523,ime:'Mislav',prezime:'Ivanda'},
    lijecnik: {maticni_broj:102523,ime:'Mislav',prezime:'Ivanda'},
    zapisnicar: {maticni_broj:199523,ime:'Mislav',prezime:'Ivanda'},
    mjerac_vremena: {maticni_broj:159511,ime:'Mislav',prezime:'Ivanda'},
    sudac1: {maticni_broj:159569,ime:'Mislav',prezime:'Ivanda'},
    sudac2: {maticni_broj:100523,ime:'Mislav',prezime:'Ivanda'},
    domaciRez:26,
    gostiRez:24,
    timDomaci:{
    id:12685,
    naziv:'RK PPD ZAGREB',
    grb:klub1,
    Igraci:[
        {
            maticni_broj:'128852',
            broj_dresa:6,
            ime:'Mislav',
            prezime:'Ivanda',
            golovi:5,
            iskljucenja:2,
            zuti:0,
            crveni:0,
            plavi:0
        },
        {
            maticni_broj:'12852',
            broj_dresa:6,
            ime:'Mislav',
            prezime:'Ivanda',
            golovi:5,
            iskljucenja:2,
            zuti:0,
            crveni:0,
            plavi:0
        },
        {
            maticni_broj:'12885',
            broj_dresa:6,
            ime:'Mislav',
            prezime:'Ivanda',
            golovi:5,
            iskljucenja:2,
            zuti:0,
            crveni:0,
            plavi:0
        },
        {
            maticni_broj:'18852',
            broj_dresa:6,
            ime:'Mislav',
            prezime:'Ivanda',
            golovi:5,
            iskljucenja:2,
            zuti:0,
            crveni:0,
            plavi:0
        },
        {
            maticni_broj:'28852',
            broj_dresa:6,
            ime:'Mislav',
            prezime:'Ivanda',
            golovi:5,
            iskljucenja:2,
            zuti:0,
            crveni:0,
            plavi:0
        },
        {
            maticni_broj:'1282',
            broj_dresa:6,
            ime:'Mislav',
            prezime:'Ivanda',
            golovi:5,
            iskljucenja:2,
            zuti:0,
            crveni:0,
            plavi:0
        },
        {
            maticni_broj:'122',
            broj_dresa:6,
            ime:'Mislav',
            prezime:'Ivanda',
            golovi:5,
            iskljucenja:2,
            zuti:0,
            crveni:0,
            plavi:0
        },
        {
            maticni_broj:'2885',
            broj_dresa:6,
            ime:'Mislav',
            prezime:'Ivanda',
            golovi:5,
            iskljucenja:2,
            zuti:0,
            crveni:0,
            plavi:0
        },
        {
            maticni_broj:'8852',
            broj_dresa:6,
            ime:'Mislav',
            prezime:'Ivanda',
            golovi:5,
            iskljucenja:2,
            zuti:0,
            crveni:0,
            plavi:0
        },
        {
            maticni_broj:'2852',
            broj_dresa:6,
            ime:'Mislav',
            prezime:'Ivanda',
            golovi:5,
            iskljucenja:2,
            zuti:0,
            crveni:0,
            plavi:0
        },
        {
            maticni_broj:'852',
            broj_dresa:6,
            ime:'Mislav',
            prezime:'Ivanda',
            golovi:5,
            iskljucenja:2,
            zuti:0,
            crveni:0,
            plavi:0
        },
        {
            maticni_broj:'188',
            broj_dresa:6,
            ime:'Mislav',
            prezime:'Ivanda',
            golovi:5,
            iskljucenja:2,
            zuti:0,
            crveni:0,
            plavi:0
        }
    ],
    Golmani:[  
    {
        maticni_broj:'1282',
        broj_dresa:6,
        ime:'Mislav',
        prezime:'Ivanda',
        golovi:5,
        iskljucenja:2,
        zuti:0,
        crveni:0,
        plavi:0,
        obrane:8
    },
    {
        maticni_broj:'12742',
        broj_dresa:6,
        ime:'Mislav',
        prezime:'Ivanda',
        golovi:5,
        iskljucenja:2,
        zuti:0,
        crveni:0,
        plavi:0,
        obrane:8
    }
],
    Stozer:[
    {
            maticni_broj:'1252',
            ime:'Mislav',
            prezime:'Ivanda',
            zuti:1,
            crveni:0,
            plavi:0,
            titula:'Trener'
    },
    {
            maticni_broj:'1852',
            ime:'Mislav',
            prezime:'Ivanda',
            zuti:1,
            crveni:0,
            plavi:0,
            titula:'Službeni predstavnik'
    },
    {
            maticni_broj:'1523',
            ime:'Mislav',
            prezime:'Ivanda',
            zuti:1,
            crveni:0,
            plavi:0,
            titula:'Tehniko'
    },
    {
            maticni_broj:'1578',
            ime:'Mislav',
            prezime:'Ivanda',
            zuti:1,
            crveni:0,
            plavi:0,
            titula:'Fiziotarapeut'
    }
    ]
},
timGosti:{
    id:120185,
    naziv:'RK BARCELONA',
    grb:klub2,
    Igraci:[
        {
            maticni_broj:'120052',
            broj_dresa:6,
            ime:'Mislav',
            prezime:'Ivanda',
            golovi:5,
            iskljucenja:2,
            zuti:0,
            crveni:0,
            plavi:0
        },
        {
            maticni_broj:'1784152',
            broj_dresa:6,
            ime:'Mislav',
            prezime:'Ivanda',
            golovi:5,
            iskljucenja:2,
            zuti:0,
            crveni:0,
            plavi:0
        },
        {
            maticni_broj:'987485',
            broj_dresa:6,
            ime:'Mislav',
            prezime:'Ivanda',
            golovi:5,
            iskljucenja:2,
            zuti:0,
            crveni:0,
            plavi:0
        },
        {
            maticni_broj:'3965152',
            broj_dresa:6,
            ime:'Mislav',
            prezime:'Ivanda',
            golovi:5,
            iskljucenja:2,
            zuti:0,
            crveni:0,
            plavi:0
        },
        {
            maticni_broj:'2041552',
            broj_dresa:6,
            ime:'Mislav',
            prezime:'Ivanda',
            golovi:5,
            iskljucenja:2,
            zuti:0,
            crveni:0,
            plavi:0
        },
        {
            maticni_broj:'12827402',
            broj_dresa:6,
            ime:'Mislav',
            prezime:'Ivanda',
            golovi:5,
            iskljucenja:2,
            zuti:0,
            crveni:0,
            plavi:0
        },
        {
            maticni_broj:'1782369',
            broj_dresa:6,
            ime:'Mislav',
            prezime:'Ivanda',
            golovi:5,
            iskljucenja:2,
            zuti:0,
            crveni:0,
            plavi:0
        },
        {
            maticni_broj:'2703655',
            broj_dresa:6,
            ime:'Mislav',
            prezime:'Ivanda',
            golovi:5,
            iskljucenja:2,
            zuti:0,
            crveni:0,
            plavi:0
        },
        {
            maticni_broj:'874102',
            broj_dresa:6,
            ime:'Mislav',
            prezime:'Ivanda',
            golovi:5,
            iskljucenja:2,
            zuti:0,
            crveni:0,
            plavi:0
        },
        {
            maticni_broj:'284360',
            broj_dresa:6,
            ime:'Mislav',
            prezime:'Ivanda',
            golovi:5,
            iskljucenja:2,
            zuti:0,
            crveni:0,
            plavi:0
        },
        {
            maticni_broj:'8570256',
            broj_dresa:6,
            ime:'Mislav',
            prezime:'Ivanda',
            golovi:5,
            iskljucenja:2,
            zuti:0,
            crveni:0,
            plavi:0
        },
        {
            maticni_broj:'187803',
            broj_dresa:6,
            ime:'Mislav',
            prezime:'Ivanda',
            golovi:5,
            iskljucenja:2,
            zuti:0,
            crveni:0,
            plavi:0
        }
    ],
    Golmani:[
        {
        maticni_broj:'132642',
        broj_dresa:6,
        ime:'Mislav',
        prezime:'Ivanda',
        golovi:5,
        iskljucenja:2,
        zuti:0,
        crveni:0,
        plavi:0,
        obrane:8
    },
    {
        maticni_broj:'174552',
        broj_dresa:6,
        ime:'Mislav',
        prezime:'Ivanda',
        golovi:5,
        iskljucenja:2,
        zuti:0,
        crveni:0,
        plavi:0,
        obrane:8
    }
],
    Stozer:[
    {
            maticni_broj:'178552',
            ime:'Mislav',
            prezime:'Ivanda',
            zuti:1,
            crveni:0,
            plavi:0,
            titula:'Trener'
    },
    {
            maticni_broj:'1852896',
            ime:'Mislav',
            prezime:'Ivanda',
            zuti:1,
            crveni:0,
            plavi:0,
            titula:'Službeni predstavnik'
    },
    {
            maticni_broj:'325452',
            ime:'Mislav',
            prezime:'Ivanda',
            zuti:1,
            crveni:0,
            plavi:0,
            titula:'Tehniko'
    },
    {
            maticni_broj:'15698',
            ime:'Mislav',
            prezime:'Ivanda',
            zuti:1,
            crveni:0,
            plavi:0,
            titula:'Fiziotarapeut'
        }
    ]
},
dogadaji:[
    {
        id:1,
        vrijeme:'53:21',
        klubgrb:1,//onzake 1 i 2 oznacavaju je li dogadaj pripada prvom ili drugom klubu
        domaci:13,
        gosti:11,
        ime:'Mislav',
        prezime:'Ivanda',
        naziv_dogadaja:'Gol',
        tip:1
    },
    {
        id:2,
        vrijeme:'53:21',
        klubgrb:2,//onzake 1 i 2 oznacavaju je li dogadaj pripada prvom ili drugom klubu
        domaci:13,
        gosti:12,
        ime:'Mislav',
        prezime:'Ivanda',
        naziv_dogadaja:'Gol',
        tip:1
    },
    {
        id:3,
        vrijeme:'53:21',
        klubgrb:2,//onzake 1 i 2 oznacavaju je li dogadaj pripada prvom ili drugom klubu
        ime:'Mislav',
        prezime:'Ivanda',
        naziv_dogadaja:'Iskljucenje',
        tip:3
    },
    {
        id:4,
        vrijeme:'53:21',
        klubgrb:1,//onzake 1 i 2 oznacavaju je li dogadaj pripada prvom ili drugom klubu
        ime:'Mislav',
        prezime:'Ivanda',
        naziv_dogadaja:'Zuti karton',
        tip:3
    },
    {
        id:5,
        vrijeme:'53:21',
        klubgrb:1,//onzake 1 i 2 oznacavaju je li dogadaj pripada prvom ili drugom klubu
        naziv_dogadaja:'Timeout domaći',
        tip:2
    },
    {
        id:6,
        vrijeme:'53:21',
        klubgrb:2,//onzake 1 i 2 oznacavaju je li dogadaj pripada prvom ili drugom klubu
        naziv_dogadaja:'Timeout gosti',
        tip:2
    }
]
};
export default utakmica;